import { Inter } from 'next/font/google'
import { ThemeProvider } from "@/components/theme-provider"

import "@/styles/css/all.css"
// import "waveform-playlist/styles/playlist.css"
import './globals.css'
import "@/styles/custom.css"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Timelineβios',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="!scroll-smooth" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider >
      </body>
    </html>
  )
}
