import { Inter } from 'next/font/google'
import "@/styles/css/all.css"
import "waveform-playlist/styles/playlist.css"
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Timelineβios',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
